// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.API.Data.Context;

namespace SmartSchool.API.Migrations
{
    [DbContext(typeof(SmartSchoolContextSqlite))]
    [Migration("20210604142437_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SmartSchool.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Name = "Ciência da Computação"
                        },
                        new
                        {
                            CourseId = 2,
                            Name = "Sistema de Informação"
                        },
                        new
                        {
                            CourseId = 3,
                            Name = "Engenharia de Software"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequeridDisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RequeridDisciplineId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseHours = 0,
                            CourseId = 1,
                            Name = "Matemática",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseHours = 0,
                            CourseId = 1,
                            Name = "Física",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseHours = 0,
                            CourseId = 1,
                            Name = "Matemática",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseHours = 0,
                            CourseId = 2,
                            Name = "Inglês",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseHours = 0,
                            CourseId = 2,
                            Name = "Programação",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseHours = 0,
                            CourseId = 2,
                            Name = "Matemática",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 7,
                            CourseHours = 0,
                            CourseId = 3,
                            Name = "Física",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 8,
                            CourseHours = 0,
                            CourseId = 3,
                            Name = "Programação",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseHours = 0,
                            CourseId = 3,
                            Name = "Programação",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseHours = 0,
                            CourseId = 1,
                            Name = "Programação",
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BirthDate = new DateTime(2008, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marta",
                            Phone = "33225555",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(1066),
                            StudentEnrollment = 1,
                            Surname = "Kent"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            BirthDate = new DateTime(2010, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paula",
                            Phone = "3354288",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3758),
                            StudentEnrollment = 2,
                            Surname = "Isabela"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BirthDate = new DateTime(2005, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laura",
                            Phone = "55668899",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3777),
                            StudentEnrollment = 3,
                            Surname = "Antonia"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            BirthDate = new DateTime(2003, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luiza",
                            Phone = "6565659",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3782),
                            StudentEnrollment = 4,
                            Surname = "Maria"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            BirthDate = new DateTime(1999, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucas",
                            Phone = "565685415",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3786),
                            StudentEnrollment = 5,
                            Surname = "Machado"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            BirthDate = new DateTime(1998, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pedro",
                            Phone = "456454545",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3795),
                            StudentEnrollment = 6,
                            Surname = "Alvares"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            BirthDate = new DateTime(2000, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paulo",
                            Phone = "9874512",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(3799),
                            StudentEnrollment = 7,
                            Surname = "José"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("SmartSchool.API.Models.StudentDiscipline", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("StudentsDisciplines");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 2,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(5744)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 4,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6501)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 5,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6506)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 1,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6508)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 2,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6509)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 5,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6512)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 1,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6513)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 2,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6514)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 3,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6516)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 1,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6518)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 4,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6519)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 5,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6520)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 4,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6521)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 5,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6522)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 1,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6523)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 2,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 3,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6526)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 4,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6528)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 1,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6529)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 2,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6530)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 3,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6531)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 4,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6532)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 5,
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 997, DateTimeKind.Local).AddTicks(6533)
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherEnrollment")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            Active = true,
                            Name = "Lauro",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 986, DateTimeKind.Local).AddTicks(6359),
                            Surname = "Oliveira",
                            TeacherEnrollment = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            Active = true,
                            Name = "Roberto",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 988, DateTimeKind.Local).AddTicks(2182),
                            Surname = "Soares",
                            TeacherEnrollment = 2
                        },
                        new
                        {
                            TeacherId = 3,
                            Active = true,
                            Name = "Ronaldo",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 988, DateTimeKind.Local).AddTicks(2202),
                            Surname = "Marconi",
                            TeacherEnrollment = 3
                        },
                        new
                        {
                            TeacherId = 4,
                            Active = true,
                            Name = "Rodrigo",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 988, DateTimeKind.Local).AddTicks(2204),
                            Surname = "Carvalho",
                            TeacherEnrollment = 4
                        },
                        new
                        {
                            TeacherId = 5,
                            Active = true,
                            Name = "Alexandre",
                            StartDate = new DateTime(2021, 6, 4, 11, 24, 36, 988, DateTimeKind.Local).AddTicks(2205),
                            Surname = "Montanha",
                            TeacherEnrollment = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Discipline", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Course", "Course")
                        .WithMany("Disciplines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Discipline", "RequeridDiscipline")
                        .WithMany()
                        .HasForeignKey("RequeridDisciplineId");

                    b.HasOne("SmartSchool.API.Models.Teacher", "Teacher")
                        .WithMany("DisciplineClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("RequeridDiscipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SmartSchool.API.Models.StudentCourse", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchool.API.Models.StudentDiscipline", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Discipline", "Discipline")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Student", "Student")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchool.API.Models.Course", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("SmartSchool.API.Models.Discipline", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("SmartSchool.API.Models.Student", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("SmartSchool.API.Models.Teacher", b =>
                {
                    b.Navigation("DisciplineClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
